name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: Features
    labels:
      - enhancement
      - feature
  - title: Bug Fixes
    labels:
      - bug
      - fix
  - title: Documentation
    labels:
      - documentation
      - docs
  - title: CI/CD
    labels:
      - ci
      - github-actions
  - title: Dependencies
    labels:
      - dependencies
  - title: Other Changes
    labels:
      - '*'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
no-changes-template: 'No changes since last release.'

version-resolver:
  major:
    labels:
      - major
      - breaking
  minor:
    labels:
      - minor
      - enhancement
      - feature
  patch:
    labels:
      - patch
      - bug
      - fix
      - documentation
      - dependencies
      - ci
  default: patch

exclude-labels:
  - skip-changelog

autolabeler:
  - label: feature
    branch:
      - '/feat\/.+/'
  - label: fix
    branch:
      - '/fix\/.+/'
  - label: chore
    branch:
      - '/chore\/.+/'
  - label: documentation
    branch:
      - '/docs?\/.+/'
